Materials:
    
    # Material: <base number>
    
    DIAMOND_AXE: 3
    DIAMOND_BOOTS: 4
    DIAMOND_CHESTPLATE: 8
    DIAMOND_HELMET: 5
    DIAMOND_HOE: 2
    DIAMOND_LEGGINGS: 7
    DIAMOND_PICKAXE: 3
    DIAMOND_SPADE: 1
    DIAMOND_SWORD: 2
    GOLD_AXE: 3
    GOLD_BOOTS: 4
    GOLD_CHESTPLATE: 8
    GOLD_HELMET: 5
    GOLD_HOE: 2
    GOLD_LEGGINGS: 7
    GOLD_PICKAXE: 3
    GOLD_SPADE: 1
    GOLD_SWORD: 2
    IRON_AXE: 3
    IRON_BOOTS: 4
    IRON_CHESTPLATE: 8
    IRON_HELMET: 5
    IRON_HOE: 2
    IRON_LEGGINGS: 7
    IRON_PICKAXE: 3
    IRON_SPADE: 1
    IRON_SWORD: 2